-- Pipeline Catalog Portal — DDL
-- Run against PRD_EDW_STG.UAM_MONITORING
--
-- ERD:
--   PIPELINE_CATALOG  1 ──< PIPELINE_CATALOG_ENTITY  (one pipeline → many entities/streams)
--   PIPELINE_CATALOG  1 ──< CATALOG_LINEAGE
--   PIPELINE_CATALOG  1 ──< CATALOG_DIAGRAMS
--   PIPELINE_CATALOG  1 ──< CATALOG_DOCUMENTS

CREATE TABLE IF NOT EXISTS PIPELINE_CATALOG (
    CATALOG_ID              VARCHAR(36)   NOT NULL PRIMARY KEY,
    PLATFORM                VARCHAR(100)  NOT NULL,
    PIPELINE_NAME           VARCHAR(500)  NOT NULL,
    PIPELINE_DESCRIPTION    TEXT,
    BUSINESS_SEGMENT        VARCHAR(200),
    DATA_PROVIDER           VARCHAR(300),
    DATA_DIRECTION          VARCHAR(50),
    CONNECTION_TYPE         VARCHAR(100),
    DATA_ENVIRONMENT        VARCHAR(50),
    OWNER_NAME              VARCHAR(200),
    OWNER_EMAIL             VARCHAR(300),
    ENGINEER_NAME           VARCHAR(200),
    ENGINEER_EMAIL          VARCHAR(300),
    IS_DOCUMENTED           BOOLEAN       DEFAULT FALSE,
    TAGS                    VARIANT,
    DATA_CLASSIFICATION     VARCHAR(50)   DEFAULT 'INTERNAL',
    REFRESH_FREQUENCY       VARCHAR(50),
    CATALOG_STATUS          VARCHAR(50)   DEFAULT 'ACTIVE',
    DEPRECATION_DATE        DATE,
    LAST_CATALOG_UPDATE     TIMESTAMP_NTZ,
    UPDATED_BY              VARCHAR(200),
    CREATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY              VARCHAR(200),

    UNIQUE (PLATFORM, PIPELINE_NAME)
);

-- Child table: one row per entity (stream/table/flow) within a pipeline
CREATE TABLE IF NOT EXISTS PIPELINE_CATALOG_ENTITY (
    ENTITY_ID               VARCHAR(36)   NOT NULL PRIMARY KEY,
    CATALOG_ID              VARCHAR(36)   NOT NULL,
    ENTITY_NAME             VARCHAR(500)  NOT NULL,
    ENTITY_DESCRIPTION      TEXT,
    DATABASE_DETAILS        VARCHAR(2000),
    URI                     VARCHAR(2000),
    CREATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY              VARCHAR(200),

    UNIQUE (CATALOG_ID, ENTITY_NAME),
    FOREIGN KEY (CATALOG_ID) REFERENCES PIPELINE_CATALOG (CATALOG_ID)
);

CREATE TABLE IF NOT EXISTS CATALOG_LINEAGE (
    LINEAGE_ID          VARCHAR(36)   NOT NULL PRIMARY KEY,
    SOURCE_CATALOG_ID   VARCHAR(36)   NOT NULL,
    TARGET_CATALOG_ID   VARCHAR(36)   NOT NULL,
    RELATIONSHIP_TYPE   VARCHAR(50)   NOT NULL,
    DESCRIPTION         VARCHAR(1000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY          VARCHAR(200),

    UNIQUE (SOURCE_CATALOG_ID, TARGET_CATALOG_ID),
    FOREIGN KEY (SOURCE_CATALOG_ID) REFERENCES PIPELINE_CATALOG (CATALOG_ID),
    FOREIGN KEY (TARGET_CATALOG_ID) REFERENCES PIPELINE_CATALOG (CATALOG_ID)
);

CREATE TABLE IF NOT EXISTS CATALOG_DIAGRAMS (
    DIAGRAM_ID          VARCHAR(36)   NOT NULL PRIMARY KEY,
    CATALOG_ID          VARCHAR(36)   NOT NULL,
    TITLE               VARCHAR(300)  NOT NULL,
    URL                 VARCHAR(2000) NOT NULL,
    DIAGRAM_TYPE        VARCHAR(50),
    THUMBNAIL_URL       VARCHAR(2000),
    DESCRIPTION         VARCHAR(1000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY          VARCHAR(200),

    FOREIGN KEY (CATALOG_ID) REFERENCES PIPELINE_CATALOG (CATALOG_ID)
);

CREATE TABLE IF NOT EXISTS CATALOG_DOCUMENTS (
    DOCUMENT_ID         VARCHAR(36)   NOT NULL PRIMARY KEY,
    CATALOG_ID          VARCHAR(36)   NOT NULL,
    TITLE               VARCHAR(300)  NOT NULL,
    URL                 VARCHAR(2000) NOT NULL,
    DOC_TYPE            VARCHAR(50),
    DESCRIPTION         VARCHAR(1000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY          VARCHAR(200),

    FOREIGN KEY (CATALOG_ID) REFERENCES PIPELINE_CATALOG (CATALOG_ID)
);
