"""SQL queries matching the 6 Snowflake analytics views.

These execute the same logic as V_PIPELINE_HEALTH_SUMMARY etc.
directly against MONITORING_EVENTS / CYCLE_STATUS_LOGS, so the
views don't need to be deployed first.
"""

HEALTH_SUMMARY = """
SELECT
    COUNT(*)                                                        AS TOTAL_RUNS,
    SUM(CASE WHEN STATUS = 'SUCCESS'   THEN 1 ELSE 0 END)          AS SUCCESSFUL_RUNS,
    SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END)          AS FAILED_RUNS,
    SUM(CASE WHEN STATUS = 'CANCELLED' THEN 1 ELSE 0 END)          AS CANCELLED_RUNS,
    ROUND(
        SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END) * 100.0
        / NULLIF(COUNT(*), 0), 1
    )                                                               AS SUCCESS_RATE_PCT,
    ROUND(AVG(DURATION_SECONDS), 1)                                 AS AVG_DURATION_SECONDS,
    COUNT(DISTINCT PLATFORM)                                        AS ACTIVE_PLATFORMS,
    COUNT(DISTINCT JOB_NAME)                                        AS UNIQUE_JOBS,
    MIN(EVENT_TIME)                                                 AS EARLIEST_EVENT,
    MAX(EVENT_TIME)                                                 AS LATEST_EVENT
FROM MONITORING_EVENTS
WHERE EVENT_TIME >= DATEADD(hour, -24, CURRENT_TIMESTAMP())
"""

STATUS_TREND = """
SELECT
    DATE_TRUNC('hour', EVENT_TIME)      AS PERIOD,
    PLATFORM,
    STATUS,
    COUNT(*)                            AS RUN_COUNT,
    ROUND(AVG(DURATION_SECONDS), 1)     AS AVG_DURATION_SECONDS
FROM MONITORING_EVENTS
WHERE EVENT_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP())
GROUP BY DATE_TRUNC('hour', EVENT_TIME), PLATFORM, STATUS
ORDER BY PERIOD DESC
"""

PLATFORM_BREAKDOWN = """
SELECT
    PLATFORM,
    STATUS,
    COUNT(*)                            AS RUN_COUNT,
    ROUND(AVG(DURATION_SECONDS), 1)     AS AVG_DURATION_SECONDS,
    ROUND(
        SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END) * 100.0
        / NULLIF(COUNT(*), 0), 1
    )                                   AS SUCCESS_RATE_PCT,
    COUNT(DISTINCT JOB_NAME)            AS UNIQUE_JOBS,
    MAX(EVENT_TIME)                     AS LAST_RUN_TIME
FROM MONITORING_EVENTS
WHERE EVENT_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP())
GROUP BY PLATFORM, STATUS
ORDER BY PLATFORM, STATUS
"""

RECENT_FAILURES = """
SELECT
    EVENT_TIME,
    PLATFORM,
    JOB_NAME,
    RUN_ID,
    STATUS,
    DURATION_SECONDS,
    ERROR_MESSAGE,
    LOG_URL,
    CORRELATION_ID,
    DATEDIFF(minute, EVENT_TIME, CURRENT_TIMESTAMP()) AS MINUTES_AGO
FROM MONITORING_EVENTS
WHERE STATUS = 'FAILED'
  AND EVENT_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIME DESC
LIMIT 50
"""

CYCLE_PERFORMANCE = """
SELECT
    CYCLE_TIMESTAMP,
    CORRELATION_ID,
    STATUS,
    DURATION_SECONDS,
    TOTAL_RUNS,
    SUCCESSFUL_ADAPTERS,
    FAILED_ADAPTERS,
    STORED_RUNS,
    STORAGE_FAILURES,
    NOTIFICATIONS_SENT,
    ROUND(
        SUCCESSFUL_ADAPTERS * 100.0
        / NULLIF(SUCCESSFUL_ADAPTERS + FAILED_ADAPTERS, 0), 1
    )                                   AS ADAPTER_SUCCESS_RATE_PCT
FROM CYCLE_STATUS_LOGS
WHERE CYCLE_TIMESTAMP >= DATEADD(day, -7, CURRENT_TIMESTAMP())
ORDER BY CYCLE_TIMESTAMP DESC
LIMIT 100
"""

PLATFORMS = """
SELECT DISTINCT UPPER(PLATFORM) AS PLATFORM
FROM PRD_EDW_STG.UAM_MONITORING.JOB_REGISTRY
ORDER BY PLATFORM
"""

JOB_PERFORMANCE = """
SELECT
    PLATFORM,
    JOB_NAME,
    COUNT(*)                                                        AS TOTAL_RUNS,
    SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END)            AS SUCCESSFUL_RUNS,
    SUM(CASE WHEN STATUS = 'FAILED'  THEN 1 ELSE 0 END)            AS FAILED_RUNS,
    ROUND(
        SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END) * 100.0
        / NULLIF(COUNT(*), 0), 1
    )                                                               AS SUCCESS_RATE_PCT,
    ROUND(AVG(DURATION_SECONDS), 1)                                 AS AVG_DURATION_SECONDS,
    ROUND(MAX(DURATION_SECONDS), 1)                                 AS MAX_DURATION_SECONDS,
    MAX(EVENT_TIME)                                                 AS LAST_RUN_TIME,
    MIN(EVENT_TIME)                                                 AS FIRST_SEEN
FROM MONITORING_EVENTS
WHERE EVENT_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
GROUP BY PLATFORM, JOB_NAME
ORDER BY FAILED_RUNS DESC, TOTAL_RUNS DESC
"""
