"""SQL queries for pipeline analytics.

Legacy mode queries physical tables (MONITORING_EVENTS / CYCLE_STATUS_LOGS).
When USE_SEMANTIC_VIEWS=true, queries come from semantic_queries (SEMANTIC_VIEW).
"""

from __future__ import annotations

import os

from app import semantic_queries as _semantic

_USE_SEMANTIC_VIEWS = os.environ.get("USE_SEMANTIC_VIEWS", "false").lower() in (
    "1",
    "true",
    "yes",
)

LEGACY_HEALTH_SUMMARY = """
SELECT
    COUNT(*)                                                        AS TOTAL_RUNS,
    SUM(CASE WHEN STATUS = 'SUCCESS'   THEN 1 ELSE 0 END)          AS SUCCESSFUL_RUNS,
    SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END)          AS FAILED_RUNS,
    SUM(CASE WHEN STATUS = 'CANCELLED' THEN 1 ELSE 0 END)          AS CANCELLED_RUNS,
    ROUND(
        SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END) * 100.0
        / NULLIF(COUNT(*), 0), 1
    )                                                               AS SUCCESS_RATE_PCT,
    ROUND(AVG(DURATION_SECONDS), 1)                                 AS AVG_DURATION_SECONDS,
    COUNT(DISTINCT PLATFORM)                                        AS ACTIVE_PLATFORMS,
    COUNT(DISTINCT JOB_NAME)                                        AS UNIQUE_JOBS,
    MIN(EVENT_TIME)                                                 AS EARLIEST_EVENT,
    MAX(EVENT_TIME)                                                 AS LATEST_EVENT
FROM MONITORING_EVENTS
WHERE EVENT_TIME >= DATEADD(hour, -24, CURRENT_TIMESTAMP())
"""

LEGACY_STATUS_TREND = """
SELECT
    DATE_TRUNC('hour', EVENT_TIME)      AS PERIOD,
    PLATFORM,
    STATUS,
    COUNT(*)                            AS RUN_COUNT,
    ROUND(AVG(DURATION_SECONDS), 1)     AS AVG_DURATION_SECONDS
FROM MONITORING_EVENTS
WHERE EVENT_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP())
GROUP BY DATE_TRUNC('hour', EVENT_TIME), PLATFORM, STATUS
ORDER BY PERIOD DESC
"""

LEGACY_PLATFORM_BREAKDOWN = """
SELECT
    PLATFORM,
    STATUS,
    COUNT(*)                            AS RUN_COUNT,
    ROUND(AVG(DURATION_SECONDS), 1)     AS AVG_DURATION_SECONDS,
    ROUND(
        SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END) * 100.0
        / NULLIF(COUNT(*), 0), 1
    )                                   AS SUCCESS_RATE_PCT,
    COUNT(DISTINCT JOB_NAME)            AS UNIQUE_JOBS,
    MAX(EVENT_TIME)                     AS LAST_RUN_TIME
FROM MONITORING_EVENTS
WHERE EVENT_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP())
GROUP BY PLATFORM, STATUS
ORDER BY PLATFORM, STATUS
"""

LEGACY_RECENT_FAILURES = """
SELECT
    EVENT_TIME,
    PLATFORM,
    JOB_NAME,
    RUN_ID,
    STATUS,
    DURATION_SECONDS,
    ERROR_MESSAGE,
    LOG_URL,
    CORRELATION_ID,
    DATEDIFF(minute, EVENT_TIME, CURRENT_TIMESTAMP()) AS MINUTES_AGO
FROM MONITORING_EVENTS
WHERE STATUS = 'FAILED'
  AND EVENT_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIME DESC
LIMIT 50
"""

LEGACY_CYCLE_PERFORMANCE = """
SELECT
    CYCLE_TIMESTAMP,
    CORRELATION_ID,
    STATUS,
    DURATION_SECONDS,
    TOTAL_RUNS,
    SUCCESSFUL_ADAPTERS,
    FAILED_ADAPTERS,
    STORED_RUNS,
    STORAGE_FAILURES,
    NOTIFICATIONS_SENT,
    ROUND(
        SUCCESSFUL_ADAPTERS * 100.0
        / NULLIF(SUCCESSFUL_ADAPTERS + FAILED_ADAPTERS, 0), 1
    )                                   AS ADAPTER_SUCCESS_RATE_PCT
FROM CYCLE_STATUS_LOGS
WHERE CYCLE_TIMESTAMP >= DATEADD(day, -7, CURRENT_TIMESTAMP())
ORDER BY CYCLE_TIMESTAMP DESC
LIMIT 100
"""

PLATFORMS = """
SELECT DISTINCT UPPER(PLATFORM) AS PLATFORM
FROM PRD_EDW_STG.UAM_MONITORING.JOB_REGISTRY
ORDER BY PLATFORM
"""

LEGACY_JOB_PERFORMANCE = """
SELECT
    UPPER(e.PLATFORM)                                               AS PLATFORM,
    COALESCE(MAX(r.JOB_NAME), e.JOB_NAME)                          AS JOB_NAME,
    COUNT(*)                                                        AS TOTAL_RUNS,
    SUM(CASE WHEN e.STATUS = 'SUCCESS' THEN 1 ELSE 0 END)          AS SUCCESSFUL_RUNS,
    SUM(CASE WHEN e.STATUS = 'FAILED'  THEN 1 ELSE 0 END)          AS FAILED_RUNS,
    ROUND(
        SUM(CASE WHEN e.STATUS = 'SUCCESS' THEN 1 ELSE 0 END) * 100.0
        / NULLIF(COUNT(*), 0), 1
    )                                                               AS SUCCESS_RATE_PCT,
    ROUND(AVG(e.DURATION_SECONDS), 1)                               AS AVG_DURATION_SECONDS,
    ROUND(MAX(e.DURATION_SECONDS), 1)                               AS MAX_DURATION_SECONDS,
    MAX(e.EVENT_TIME)                                               AS LAST_RUN_TIME,
    MIN(e.EVENT_TIME)                                               AS FIRST_SEEN,
    MAX(r.PLATFORM_METADATA:solution_id::STRING)                    AS SOLUTION_ID,
    MAX(r.PLATFORM_METADATA:solution_name::STRING)                  AS SOLUTION_NAME,
    MAX(
        COALESCE(
            r.PLATFORM_METADATA:tag::STRING,
            r.PLATFORM_METADATA:Tag::STRING,
            r.PLATFORM_METADATA:TAG::STRING
        )
    )                                                               AS TAG
FROM MONITORING_EVENTS e
LEFT JOIN PRD_EDW_STG.UAM_MONITORING.JOB_REGISTRY r
    ON UPPER(r.PLATFORM) = UPPER(e.PLATFORM)
   AND (
        UPPER(NULLIF(TRIM(r.JOB_ID), '')) = UPPER(TRIM(e.JOB_NAME))
        OR UPPER(TRIM(r.JOB_NAME)) = UPPER(TRIM(e.JOB_NAME))
    )
WHERE e.EVENT_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
GROUP BY UPPER(e.PLATFORM), e.JOB_NAME
ORDER BY FAILED_RUNS DESC, TOTAL_RUNS DESC
"""

MONITORING_EVENTS = """
SELECT
    PLATFORM,
    JOB_NAME,
    EVENT_TYPE,
    STATUS,
    START_TIME,
    END_TIME,
    DURATION_SECONDS,
    PLATFORM_METADATA
FROM PRD_EDW_STG.UAM_MONITORING.MONITORING_EVENTS
WHERE EVENT_TIME >= DATEADD('day', -14, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIME DESC
"""

JOB_REGISTRY = """
SELECT
    UPPER(PLATFORM)                                AS PLATFORM,
    JOB_NAME,
    PRIORITY,
    DESCRIPTION,
    BUSINESS_FUNCTION,
    SLA_HOURS,
    ENABLED,
    PLATFORM_METADATA:solution_id::STRING          AS SOLUTION_ID,
    PLATFORM_METADATA:solution_name::STRING        AS SOLUTION_NAME,
    PLATFORM_METADATA:category::STRING             AS CATEGORY,
    PLATFORM_METADATA:flow_type::STRING            AS FLOW_TYPE,
    COALESCE(
        PLATFORM_METADATA:tag::STRING,
        PLATFORM_METADATA:Tag::STRING,
        PLATFORM_METADATA:TAG::STRING
    )                                              AS TAG
FROM PRD_EDW_STG.UAM_MONITORING.JOB_REGISTRY
ORDER BY UPPER(PLATFORM), JOB_NAME
"""

HEALTH_SUMMARY = (
    _semantic.HEALTH_SUMMARY if _USE_SEMANTIC_VIEWS else LEGACY_HEALTH_SUMMARY
)
STATUS_TREND = (
    _semantic.STATUS_TREND if _USE_SEMANTIC_VIEWS else LEGACY_STATUS_TREND
)
PLATFORM_BREAKDOWN = (
    _semantic.PLATFORM_BREAKDOWN
    if _USE_SEMANTIC_VIEWS
    else LEGACY_PLATFORM_BREAKDOWN
)
RECENT_FAILURES = (
    _semantic.RECENT_FAILURES if _USE_SEMANTIC_VIEWS else LEGACY_RECENT_FAILURES
)
CYCLE_PERFORMANCE = (
    _semantic.CYCLE_PERFORMANCE if _USE_SEMANTIC_VIEWS else LEGACY_CYCLE_PERFORMANCE
)
JOB_PERFORMANCE = (
    _semantic.JOB_PERFORMANCE if _USE_SEMANTIC_VIEWS else LEGACY_JOB_PERFORMANCE
)
